// 本文件由 scripts/gen_mavlink_defs.py 自动生成, 请勿手工编辑。
// 数据来源: pymavlink common + ardupilotmega 方言

export const MAVLINK_DEFS = {
  HEARTBEAT: {
    id: 0,
    crcExtra: 50,
    v1Size: 9,
    v1Fields: ['custom_mode', 'type', 'autopilot', 'base_mode', 'system_status', 'mavlink_version'],
    size: 9,
    fields: [
      { name: 'custom_mode', type: 'u32', len: 0 },
      { name: 'type', type: 'u8', len: 0 },
      { name: 'autopilot', type: 'u8', len: 0 },
      { name: 'base_mode', type: 'u8', len: 0 },
      { name: 'system_status', type: 'u8', len: 0 },
      { name: 'mavlink_version', type: 'u8', len: 0 },
    ],
  },
  PARAM_REQUEST_READ: {
    id: 20,
    crcExtra: 214,
    v1Size: 20,
    v1Fields: ['param_index', 'target_system', 'target_component', 'param_id'],
    size: 20,
    fields: [
      { name: 'param_index', type: 'i16', len: 0 },
      { name: 'target_system', type: 'u8', len: 0 },
      { name: 'target_component', type: 'u8', len: 0 },
      { name: 'param_id', type: 'char', len: 16 },
    ],
  },
  PARAM_REQUEST_LIST: {
    id: 21,
    crcExtra: 159,
    v1Size: 2,
    v1Fields: ['target_system', 'target_component'],
    size: 2,
    fields: [
      { name: 'target_system', type: 'u8', len: 0 },
      { name: 'target_component', type: 'u8', len: 0 },
    ],
  },
  PARAM_VALUE: {
    id: 22,
    crcExtra: 220,
    v1Size: 25,
    v1Fields: ['param_value', 'param_count', 'param_index', 'param_id', 'param_type'],
    size: 25,
    fields: [
      { name: 'param_value', type: 'f32', len: 0 },
      { name: 'param_count', type: 'u16', len: 0 },
      { name: 'param_index', type: 'u16', len: 0 },
      { name: 'param_id', type: 'char', len: 16 },
      { name: 'param_type', type: 'u8', len: 0 },
    ],
  },
  PARAM_SET: {
    id: 23,
    crcExtra: 168,
    v1Size: 23,
    v1Fields: ['param_value', 'target_system', 'target_component', 'param_id', 'param_type'],
    size: 23,
    fields: [
      { name: 'param_value', type: 'f32', len: 0 },
      { name: 'target_system', type: 'u8', len: 0 },
      { name: 'target_component', type: 'u8', len: 0 },
      { name: 'param_id', type: 'char', len: 16 },
      { name: 'param_type', type: 'u8', len: 0 },
    ],
  },
  COMMAND_LONG: {
    id: 76,
    crcExtra: 152,
    v1Size: 33,
    v1Fields: ['param1', 'param2', 'param3', 'param4', 'param5', 'param6', 'param7', 'command', 'target_system', 'target_component', 'confirmation'],
    size: 33,
    fields: [
      { name: 'param1', type: 'f32', len: 0 },
      { name: 'param2', type: 'f32', len: 0 },
      { name: 'param3', type: 'f32', len: 0 },
      { name: 'param4', type: 'f32', len: 0 },
      { name: 'param5', type: 'f32', len: 0 },
      { name: 'param6', type: 'f32', len: 0 },
      { name: 'param7', type: 'f32', len: 0 },
      { name: 'command', type: 'u16', len: 0 },
      { name: 'target_system', type: 'u8', len: 0 },
      { name: 'target_component', type: 'u8', len: 0 },
      { name: 'confirmation', type: 'u8', len: 0 },
    ],
  },
  COMMAND_ACK: {
    id: 77,
    crcExtra: 143,
    v1Size: 3,
    v1Fields: ['command', 'result'],
    size: 10,
    fields: [
      { name: 'command', type: 'u16', len: 0 },
      { name: 'result', type: 'u8', len: 0 },
      { name: 'progress', type: 'u8', len: 0 },
      { name: 'result_param2', type: 'i32', len: 0 },
      { name: 'target_system', type: 'u8', len: 0 },
      { name: 'target_component', type: 'u8', len: 0 },
    ],
  },
  STATUSTEXT: {
    id: 253,
    crcExtra: 83,
    v1Size: 51,
    v1Fields: ['severity', 'text'],
    size: 54,
    fields: [
      { name: 'severity', type: 'u8', len: 0 },
      { name: 'text', type: 'char', len: 50 },
      { name: 'id', type: 'u16', len: 0 },
      { name: 'chunk_seq', type: 'u8', len: 0 },
    ],
  },
  ATTITUDE: {
    id: 30,
    crcExtra: 39,
    v1Size: 28,
    v1Fields: ['time_boot_ms', 'roll', 'pitch', 'yaw', 'rollspeed', 'pitchspeed', 'yawspeed'],
    size: 28,
    fields: [
      { name: 'time_boot_ms', type: 'u32', len: 0 },
      { name: 'roll', type: 'f32', len: 0 },
      { name: 'pitch', type: 'f32', len: 0 },
      { name: 'yaw', type: 'f32', len: 0 },
      { name: 'rollspeed', type: 'f32', len: 0 },
      { name: 'pitchspeed', type: 'f32', len: 0 },
      { name: 'yawspeed', type: 'f32', len: 0 },
    ],
  },
  GLOBAL_POSITION_INT: {
    id: 33,
    crcExtra: 104,
    v1Size: 28,
    v1Fields: ['time_boot_ms', 'lat', 'lon', 'alt', 'relative_alt', 'vx', 'vy', 'vz', 'hdg'],
    size: 28,
    fields: [
      { name: 'time_boot_ms', type: 'u32', len: 0 },
      { name: 'lat', type: 'i32', len: 0 },
      { name: 'lon', type: 'i32', len: 0 },
      { name: 'alt', type: 'i32', len: 0 },
      { name: 'relative_alt', type: 'i32', len: 0 },
      { name: 'vx', type: 'i16', len: 0 },
      { name: 'vy', type: 'i16', len: 0 },
      { name: 'vz', type: 'i16', len: 0 },
      { name: 'hdg', type: 'u16', len: 0 },
    ],
  },
  VFR_HUD: {
    id: 74,
    crcExtra: 20,
    v1Size: 20,
    v1Fields: ['airspeed', 'groundspeed', 'alt', 'climb', 'heading', 'throttle'],
    size: 20,
    fields: [
      { name: 'airspeed', type: 'f32', len: 0 },
      { name: 'groundspeed', type: 'f32', len: 0 },
      { name: 'alt', type: 'f32', len: 0 },
      { name: 'climb', type: 'f32', len: 0 },
      { name: 'heading', type: 'i16', len: 0 },
      { name: 'throttle', type: 'u16', len: 0 },
    ],
  },
  SYS_STATUS: {
    id: 1,
    crcExtra: 124,
    v1Size: 31,
    v1Fields: ['onboard_control_sensors_present', 'onboard_control_sensors_enabled', 'onboard_control_sensors_health', 'load', 'voltage_battery', 'current_battery', 'drop_rate_comm', 'errors_comm', 'errors_count1', 'errors_count2', 'errors_count3', 'errors_count4', 'battery_remaining'],
    size: 43,
    fields: [
      { name: 'onboard_control_sensors_present', type: 'u32', len: 0 },
      { name: 'onboard_control_sensors_enabled', type: 'u32', len: 0 },
      { name: 'onboard_control_sensors_health', type: 'u32', len: 0 },
      { name: 'load', type: 'u16', len: 0 },
      { name: 'voltage_battery', type: 'u16', len: 0 },
      { name: 'current_battery', type: 'i16', len: 0 },
      { name: 'drop_rate_comm', type: 'u16', len: 0 },
      { name: 'errors_comm', type: 'u16', len: 0 },
      { name: 'errors_count1', type: 'u16', len: 0 },
      { name: 'errors_count2', type: 'u16', len: 0 },
      { name: 'errors_count3', type: 'u16', len: 0 },
      { name: 'errors_count4', type: 'u16', len: 0 },
      { name: 'battery_remaining', type: 'i8', len: 0 },
      { name: 'onboard_control_sensors_present_extended', type: 'u32', len: 0 },
      { name: 'onboard_control_sensors_enabled_extended', type: 'u32', len: 0 },
      { name: 'onboard_control_sensors_health_extended', type: 'u32', len: 0 },
    ],
  },
  AUTOPILOT_VERSION: {
    id: 148,
    crcExtra: 178,
    v1Size: 60,
    v1Fields: ['capabilities', 'uid', 'flight_sw_version', 'middleware_sw_version', 'os_sw_version', 'board_version', 'vendor_id', 'product_id', 'flight_custom_version', 'middleware_custom_version', 'os_custom_version'],
    size: 78,
    fields: [
      { name: 'capabilities', type: 'u64', len: 0 },
      { name: 'uid', type: 'u64', len: 0 },
      { name: 'flight_sw_version', type: 'u32', len: 0 },
      { name: 'middleware_sw_version', type: 'u32', len: 0 },
      { name: 'os_sw_version', type: 'u32', len: 0 },
      { name: 'board_version', type: 'u32', len: 0 },
      { name: 'vendor_id', type: 'u16', len: 0 },
      { name: 'product_id', type: 'u16', len: 0 },
      { name: 'flight_custom_version', type: 'u8', len: 8 },
      { name: 'middleware_custom_version', type: 'u8', len: 8 },
      { name: 'os_custom_version', type: 'u8', len: 8 },
      { name: 'uid2', type: 'u8', len: 18 },
    ],
  },
  ESC_TELEMETRY_1_TO_4: {
    id: 11030,
    crcExtra: 144,
    v1Size: null,
    v1Fields: [],
    size: 44,
    fields: [
      { name: 'voltage', type: 'u16', len: 4 },
      { name: 'current', type: 'u16', len: 4 },
      { name: 'totalcurrent', type: 'u16', len: 4 },
      { name: 'rpm', type: 'u16', len: 4 },
      { name: 'count', type: 'u16', len: 4 },
      { name: 'temperature', type: 'u8', len: 4 },
    ],
  },
  LOG_REQUEST_LIST: {
    id: 117,
    crcExtra: 128,
    v1Size: 6,
    v1Fields: ['start', 'end', 'target_system', 'target_component'],
    size: 6,
    fields: [
      { name: 'start', type: 'u16', len: 0 },
      { name: 'end', type: 'u16', len: 0 },
      { name: 'target_system', type: 'u8', len: 0 },
      { name: 'target_component', type: 'u8', len: 0 },
    ],
  },
  LOG_ENTRY: {
    id: 118,
    crcExtra: 56,
    v1Size: 14,
    v1Fields: ['time_utc', 'size', 'id', 'num_logs', 'last_log_num'],
    size: 14,
    fields: [
      { name: 'time_utc', type: 'u32', len: 0 },
      { name: 'size', type: 'u32', len: 0 },
      { name: 'id', type: 'u16', len: 0 },
      { name: 'num_logs', type: 'u16', len: 0 },
      { name: 'last_log_num', type: 'u16', len: 0 },
    ],
  },
  LOG_REQUEST_DATA: {
    id: 119,
    crcExtra: 116,
    v1Size: 12,
    v1Fields: ['ofs', 'count', 'id', 'target_system', 'target_component'],
    size: 12,
    fields: [
      { name: 'ofs', type: 'u32', len: 0 },
      { name: 'count', type: 'u32', len: 0 },
      { name: 'id', type: 'u16', len: 0 },
      { name: 'target_system', type: 'u8', len: 0 },
      { name: 'target_component', type: 'u8', len: 0 },
    ],
  },
  LOG_DATA: {
    id: 120,
    crcExtra: 134,
    v1Size: 97,
    v1Fields: ['ofs', 'id', 'count', 'data'],
    size: 97,
    fields: [
      { name: 'ofs', type: 'u32', len: 0 },
      { name: 'id', type: 'u16', len: 0 },
      { name: 'count', type: 'u8', len: 0 },
      { name: 'data', type: 'u8', len: 90 },
    ],
  },
  LOG_ERASE: {
    id: 121,
    crcExtra: 237,
    v1Size: 2,
    v1Fields: ['target_system', 'target_component'],
    size: 2,
    fields: [
      { name: 'target_system', type: 'u8', len: 0 },
      { name: 'target_component', type: 'u8', len: 0 },
    ],
  },
  LOG_REQUEST_END: {
    id: 122,
    crcExtra: 203,
    v1Size: 2,
    v1Fields: ['target_system', 'target_component'],
    size: 2,
    fields: [
      { name: 'target_system', type: 'u8', len: 0 },
      { name: 'target_component', type: 'u8', len: 0 },
    ],
  },
};

export const MSG_NAME_BY_ID = {
  0: "HEARTBEAT",
  20: "PARAM_REQUEST_READ",
  21: "PARAM_REQUEST_LIST",
  22: "PARAM_VALUE",
  23: "PARAM_SET",
  76: "COMMAND_LONG",
  77: "COMMAND_ACK",
  253: "STATUSTEXT",
  30: "ATTITUDE",
  33: "GLOBAL_POSITION_INT",
  74: "VFR_HUD",
  1: "SYS_STATUS",
  148: "AUTOPILOT_VERSION",
  11030: "ESC_TELEMETRY_1_TO_4",
  117: "LOG_REQUEST_LIST",
  118: "LOG_ENTRY",
  119: "LOG_REQUEST_DATA",
  120: "LOG_DATA",
  121: "LOG_ERASE",
  122: "LOG_REQUEST_END",
};

export const MSG_ID = {
  HEARTBEAT: 0,
  PARAM_REQUEST_READ: 20,
  PARAM_REQUEST_LIST: 21,
  PARAM_VALUE: 22,
  PARAM_SET: 23,
  COMMAND_LONG: 76,
  COMMAND_ACK: 77,
  STATUSTEXT: 253,
  ATTITUDE: 30,
  GLOBAL_POSITION_INT: 33,
  VFR_HUD: 74,
  SYS_STATUS: 1,
  AUTOPILOT_VERSION: 148,
  ESC_TELEMETRY_1_TO_4: 11030,
  LOG_REQUEST_LIST: 117,
  LOG_ENTRY: 118,
  LOG_REQUEST_DATA: 119,
  LOG_DATA: 120,
  LOG_ERASE: 121,
  LOG_REQUEST_END: 122,
};
